In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])

In [ ]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [ ]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [ ]:
X=df.drop(columns=['Survived'])
Y=df['Survived']
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [ ]:
knn=KNNImputer(n_neighbors=1,weights='distance')
X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [ ]:
lr=LogisticRegression()
lr.fit(X_train_trf,Y_train)
y_pred=lr.predict(X_test_trf)
accuracy_score(Y_test,y_pred)

0.7206703910614525

In [ ]:
si=SimpleImputer()
X_train_trf2=si.fit_transform(X_train)
X_test_trf2=si.transform(X_test)
lr.fit(X_train_trf2,Y_train)
y_pred2=lr.predict(X_test_trf2)
accuracy_score(Y_test,y_pred2)

0.6927374301675978